[config]
expr_prefix  = "{{"
expr_postfix = "}}"

[templates.hyprland]
input_path = './templates/hypr/colors.lua'
output_path = '~/.config/hypr/colors.lua'
post_hook = 'hyprctl reload'

[templates.hyprland_wallpapers]
input_path = './templates/hypr/autostart.lua'
output_path = '~/.config/hypr/autostart.lua'
post_hook = 'pkill mpvpaper && mpvpaper -o "loop panscan=1" ALL "~/.local/share/wallpapers/{{wallpapers}}" &>/dev/null &'

[templates.waybar_style]
input_path = './templates/waybar/colors.scss'
output_path = '~/.config/waybar/colors.scss'
post_hook = 'sassc ~/.config/waybar/style.scss ~/.config/waybar/style.css'

[templates.waybar_cava]
input_path = './templates/cava/waybar_cava'
output_path = '~/.config/cava/waybar_cava'
